<a href="https://colab.research.google.com/github/ashmina-ashraf/DataScience/blob/main/seedsNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes  import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
df = pd.read_csv('/content/seeds.csv')
#df.head()

In [29]:
x = df.iloc[:, :-1]
y = df.iloc[:,-1]

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.40, random_state=None)

In [ ]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)


In [30]:
y_pred = gnb.predict(x_test)
y_pred

array([1, 3, 3, 2, 1, 2, 1, 1, 2, 1, 3, 2, 2, 3, 1, 1, 2, 1, 2, 1, 1, 3,
       3, 3, 2, 2, 1, 3, 1, 3, 3, 1, 1, 2, 2, 1, 1, 2, 2, 2, 3, 2, 1, 2,
       3, 3, 1, 3, 1, 1, 2, 2, 3, 2, 3, 3, 2, 3, 2, 1, 1, 2, 1, 3, 2, 3,
       1, 3, 3, 3, 3, 1, 1, 3, 3, 2, 2, 3, 2, 2, 1, 1, 2, 2])

In [31]:
print(metrics.accuracy_score(y_test, y_pred))

0.9047619047619048


In [32]:
print(metrics.confusion_matrix(y_test, y_pred))

[[26  2  4]
 [ 0 27  0]
 [ 2  0 23]]
